// <auto-generated />
using InventoryManagementSystem.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventoryManagementSystem.Db.Migrations
{
    [DbContext(typeof(InventoryManagementSystemDbContext))]
    [Migration("20240402135120_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryManagementSystem.Db.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kitchen Appliances"
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Db.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Item", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A portable computer",
                            Name = "Laptop",
                            Quantity = 10,
                            Status = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "A cotton shirt",
                            Name = "T-Shirt",
                            Quantity = 50,
                            Status = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "High-end mobile phone",
                            Name = "Smartphone",
                            Quantity = 25,
                            Status = 0,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Denim jeans",
                            Name = "Jeans",
                            Quantity = 0,
                            Status = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Electronic book reader",
                            Name = "E-Reader",
                            Quantity = 15,
                            Status = 1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Description = "Kitchen appliance",
                            Name = "Blender",
                            Quantity = 20,
                            Status = 0,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Heats food quickly and efficiently",
                            Name = "Microwave Oven",
                            Quantity = 30,
                            Status = 0,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "A novel set in a fictional universe",
                            Name = "Fantasy Novel",
                            Quantity = 50,
                            Status = 0,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Wireless over-ear headphones",
                            Name = "Headphones",
                            Quantity = 60,
                            Status = 0,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Warm wool sweater",
                            Name = "Sweater",
                            Quantity = 35,
                            Status = 0,
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Description = "LED desk lamp",
                            Name = "Lamp",
                            Quantity = 40,
                            Status = 0,
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Covers world history",
                            Name = "History Book",
                            Quantity = 20,
                            Status = 0,
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Description = "Latest generation home video game console",
                            Name = "Gaming Console",
                            Quantity = 15,
                            Status = 1,
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Lightweight and comfortable running shoes",
                            Name = "Running Shoes",
                            Quantity = 25,
                            Status = 0,
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "Space adventure novel",
                            Name = "Sci-Fi Novel",
                            Quantity = 30,
                            Status = 0,
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Description = "Automatic drip coffee maker",
                            Name = "Coffee Maker",
                            Quantity = 20,
                            Status = 0,
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Description = "Wearable technology for fitness tracking",
                            Name = "Smartwatch",
                            Quantity = 40,
                            Status = 0,
                            UserId = 17
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Description = "High-quality leather jacket",
                            Name = "Leather Jacket",
                            Quantity = 10,
                            Status = 1,
                            UserId = 18
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Description = "Collection of gourmet recipes",
                            Name = "Cookbook",
                            Quantity = 50,
                            Status = 0,
                            UserId = 19
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "Improves indoor air quality",
                            Name = "Air Purifier",
                            Quantity = 15,
                            Status = 1,
                            UserId = 20
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Description = "Portable touchscreen computer",
                            Name = "Tablet",
                            Quantity = 25,
                            Status = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            Description = "Soft cotton hoodie",
                            Name = "Hoodie",
                            Quantity = 60,
                            Status = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 4,
                            Description = "Adjustable LED desk lamp",
                            Name = "Desk Lamp",
                            Quantity = 70,
                            Status = 0,
                            UserId = 3
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Description = "Engaging and suspenseful mystery novel",
                            Name = "Mystery Novel",
                            Quantity = 80,
                            Status = 0,
                            UserId = 4
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 1,
                            Description = "1TB USB external hard drive",
                            Name = "External Hard Drive",
                            Quantity = 90,
                            Status = 0,
                            UserId = 5
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            Description = "UV protection sunglasses",
                            Name = "Sunglasses",
                            Quantity = 100,
                            Status = 0,
                            UserId = 6
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            Description = "4-slice toaster",
                            Name = "Toaster",
                            Quantity = 110,
                            Status = 0,
                            UserId = 7
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            Description = "Biography of a historical figure",
                            Name = "Biography Book",
                            Quantity = 120,
                            Status = 0,
                            UserId = 8
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 1,
                            Description = "Mechanical RGB gaming keyboard",
                            Name = "Gaming Keyboard",
                            Quantity = 130,
                            Status = 0,
                            UserId = 9
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 2,
                            Description = "Lightweight running shorts",
                            Name = "Running Shorts",
                            Quantity = 0,
                            Status = 2,
                            UserId = 10
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            Description = "Bagless cyclone vacuum cleaner",
                            Name = "Vacuum Cleaner",
                            Quantity = 150,
                            Status = 0,
                            UserId = 11
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            Description = "Guide to personal growth and productivity",
                            Name = "Self-Help Book",
                            Quantity = 160,
                            Status = 0,
                            UserId = 12
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 1,
                            Description = "High-definition USB webcam",
                            Name = "Webcam",
                            Quantity = 170,
                            Status = 0,
                            UserId = 13
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Db.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "user1@example.com",
                            Password = "$2a$11$yahCOxMg6Rwv7NYWhCS1GOJBq2tk3HGOWvkWt2spsyva0KpK3j3CG",
                            Username = "user1"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "user2@example.com",
                            Password = "$2a$11$YY381W06BNlpt3rU/on4CunDQjjD9MwD.YqYhvBzkUxH4N76qbgTy",
                            Username = "user2"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "user3@example.com",
                            Password = "$2a$11$d6s76qB5SOwxWLjQ.xfV2OMHGYtRGT9Uo52ZZvB.gQiCnyeUFhM4u",
                            Username = "user3"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "user4@example.com",
                            Password = "$2a$11$oNLEjuRPg0IxVAi9ZlbDseJ7HWva0EHLBa2GDG1b9QletYBGqmBeC",
                            Username = "user4"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "user5@example.com",
                            Password = "$2a$11$JyK1EIpy5TlgkfnpRBXL2uNYoNO7054Yw8SEVQbBEjR.vjltVJAUG",
                            Username = "user5"
                        },
                        new
                        {
                            UserId = 6,
                            Email = "user6@example.com",
                            Password = "$2a$11$Nk17MqR0b3Xy59Hio1.nqOKu8y74JvI8tiGikVtQg0cPBHsgKiGZG",
                            Username = "user6"
                        },
                        new
                        {
                            UserId = 7,
                            Email = "user7@example.com",
                            Password = "$2a$11$5GRznd0kdTlt2P3zVn7B8.ovFv2FP09BqBUBODC7zbHmjLv8kbudq",
                            Username = "user7"
                        },
                        new
                        {
                            UserId = 8,
                            Email = "user8@example.com",
                            Password = "$2a$11$HMuhTUxaNH7pEPFKkYoeTeNflRZALJtZK0f3SG3Y17IIu3ZbsJMKC",
                            Username = "user8"
                        },
                        new
                        {
                            UserId = 9,
                            Email = "user9@example.com",
                            Password = "$2a$11$6y1bNprzthgUGx15M7dsqOTFKMFB2gjvWqeW1fQLBbiDbjLZq7IXS",
                            Username = "user9"
                        },
                        new
                        {
                            UserId = 10,
                            Email = "user10@example.com",
                            Password = "$2a$11$n/HsY0ROmMh1lY7NcqvYYu4HMH0ZjWTif1hj5fmhWcHNwqRLjy1Q6",
                            Username = "user10"
                        },
                        new
                        {
                            UserId = 11,
                            Email = "user11@example.com",
                            Password = "$2a$11$UW2mRYaxWCRGo5MC3MXaTOsSI.9xtWn8uZcC/hskoUTJYZpEnVIWq",
                            Username = "user11"
                        },
                        new
                        {
                            UserId = 12,
                            Email = "user12@example.com",
                            Password = "$2a$11$rGASBo/h9dGhFWCL7wQlAuKh59FfrZzC0/vYFW2Mp5WOUGrXdlkdW",
                            Username = "user12"
                        },
                        new
                        {
                            UserId = 13,
                            Email = "user13@example.com",
                            Password = "$2a$11$YXN.tOYdO2TFrF2qxvN8FOF93QkzqkGkDX9ZCJW24HdbBV/wBZ.SG",
                            Username = "user13"
                        },
                        new
                        {
                            UserId = 14,
                            Email = "user14@example.com",
                            Password = "$2a$11$ocfn6J5zQwXdKwcH6HPso.Y9JujDvdUH/T5K5VNU6VKJrxuzvaXA6",
                            Username = "user14"
                        },
                        new
                        {
                            UserId = 15,
                            Email = "user15@example.com",
                            Password = "$2a$11$DECJGnmm0F/97PekbQuTv.li7RLcPg4NRaZaTJZf8uzRpxOL7.NDy",
                            Username = "user15"
                        },
                        new
                        {
                            UserId = 16,
                            Email = "user16@example.com",
                            Password = "$2a$11$SbV/GuevY6RPzI/8geiIwutC88vIQeH4R5UsUg6t/pjL7QmCEAW0W",
                            Username = "user16"
                        },
                        new
                        {
                            UserId = 17,
                            Email = "user17@example.com",
                            Password = "$2a$11$KiDaiCW8yAZZdKrQQ.B2veBHUjWikhYgr/N5o7cvJ9etc/MbSqYNW",
                            Username = "user17"
                        },
                        new
                        {
                            UserId = 18,
                            Email = "user18@example.com",
                            Password = "$2a$11$9JfVgE3Mv3Y0INWZ3AFN/ukG3K1J.3QB9cKpOoa1L3ivovtZ.mOla",
                            Username = "user18"
                        },
                        new
                        {
                            UserId = 19,
                            Email = "user19@example.com",
                            Password = "$2a$11$DQnGH5wwxiOJPXur2ST54u13WovBdpvS32WQ845YipS37zHVS2GHq",
                            Username = "user19"
                        },
                        new
                        {
                            UserId = 20,
                            Email = "user20@example.com",
                            Password = "$2a$11$94p7QIVaOkoJ0XuBz4nEOuB5oxvcBTwN2uYEYRIMZPVFn8O9QJ7SG",
                            Username = "user20"
                        },
                        new
                        {
                            UserId = 21,
                            Email = "user21@example.com",
                            Password = "$2a$11$khF986iNnhiHGZP/9j0OyOGMnL3oLSCfH2OCYbqSFHCteRwaKARGW",
                            Username = "user21"
                        },
                        new
                        {
                            UserId = 22,
                            Email = "user22@example.com",
                            Password = "$2a$11$WHKD05V96T5ntqqcCHWl0exy/GMi1LRn8zdL6dGxhpI4ZR43Uh3fu",
                            Username = "user22"
                        },
                        new
                        {
                            UserId = 23,
                            Email = "user23@example.com",
                            Password = "$2a$11$m1DBACOvT/.xxNxSNEtT2u6gkVRebmNeYDcRIJj5Coizvv/JqEfvC",
                            Username = "user23"
                        },
                        new
                        {
                            UserId = 24,
                            Email = "user24@example.com",
                            Password = "$2a$11$apwQorJwP6qH.fFVnk9PvOFNMm3Wy/8KiWx71A.bSeIOOlW8ZjhFC",
                            Username = "user24"
                        },
                        new
                        {
                            UserId = 25,
                            Email = "user25@example.com",
                            Password = "$2a$11$4yg2XIt4nyJNkxArdAIr8ef.60WrI3qKl2JxZQowUkDh6kGg5jD2.",
                            Username = "user25"
                        },
                        new
                        {
                            UserId = 26,
                            Email = "user26@example.com",
                            Password = "$2a$11$8U6hzveO6oN08HR6PSdFaOrpXDmxQfWW/jY1qc8n4Q.YppeUqpGsO",
                            Username = "user26"
                        },
                        new
                        {
                            UserId = 27,
                            Email = "user27@example.com",
                            Password = "$2a$11$JfPW/hsXjVzrVYRrW.nvAuUgvYnhuLjBeJDKSUDVa1kyCmuux0P8e",
                            Username = "user27"
                        },
                        new
                        {
                            UserId = 28,
                            Email = "user28@example.com",
                            Password = "$2a$11$.SX7Sxip7BnjIP.QdFlbdeOp8d6MTilDQQbKAf3b/tJUEnxdoK0ii",
                            Username = "user28"
                        },
                        new
                        {
                            UserId = 29,
                            Email = "user29@example.com",
                            Password = "$2a$11$Sdgxh3gANiHUb98XkBgGauZNClpBsSzKQjMqVmA3dPYdJtirjfG2G",
                            Username = "user29"
                        },
                        new
                        {
                            UserId = 30,
                            Email = "user30@example.com",
                            Password = "$2a$11$qhU1nFUPr8FElz/YTEAL5uIcB28zt1JBM7zjtgTz7Sd4TyVEguBhu",
                            Username = "user30"
                        },
                        new
                        {
                            UserId = 31,
                            Email = "user31@example.com",
                            Password = "$2a$11$zXCx.VrJMzJws5ocCbEeHeatUo/uKK0rAY9VantOIdMJbtqr7waie",
                            Username = "user31"
                        },
                        new
                        {
                            UserId = 32,
                            Email = "user32@example.com",
                            Password = "$2a$11$R5pBGMBzsz2WsMAvTBIOAuEoUDhYgLD/79QEuHF60O13vjg7GM1AC",
                            Username = "user32"
                        },
                        new
                        {
                            UserId = 33,
                            Email = "user33@example.com",
                            Password = "$2a$11$NemJw4/P.1Aah1ZtpuzNxOW96vu/c/eu9xZvtU9ZeynNh5x7zHUUS",
                            Username = "user33"
                        },
                        new
                        {
                            UserId = 34,
                            Email = "user34@example.com",
                            Password = "$2a$11$mjyL00CZYUNEQJHzXN2QGeooWlhxFMurPNhU8VkeExYXeuI5O4Mra",
                            Username = "user34"
                        },
                        new
                        {
                            UserId = 35,
                            Email = "user35@example.com",
                            Password = "$2a$11$UTcQUf2UaXpKcNYpDjatK.dMq/FyY2CWHuwrwn9RVTAcMVg2HgiD.",
                            Username = "user35"
                        },
                        new
                        {
                            UserId = 36,
                            Email = "user36@example.com",
                            Password = "$2a$11$ZEN7x3fk9HJazF1X8epFBuDVAX5/aUr9vgNFyPLLPfRuNKigTQ8Ou",
                            Username = "user36"
                        },
                        new
                        {
                            UserId = 37,
                            Email = "user37@example.com",
                            Password = "$2a$11$jkvdINT5nJvH7i/fcbqhsOCBAbGRaZvmDwMFBwRURTdfrJB6UCxES",
                            Username = "user37"
                        },
                        new
                        {
                            UserId = 38,
                            Email = "user38@example.com",
                            Password = "$2a$11$jhA9QiMo28s.eUPHfBKp3elE.v98QI6tttODyXhGDIo8WDMaXaWka",
                            Username = "user38"
                        },
                        new
                        {
                            UserId = 39,
                            Email = "user39@example.com",
                            Password = "$2a$11$Em3/IPqO.zAM26AM8ypWPudkmvFTAYMsjHVM.7D6SFp29WPsGnQxi",
                            Username = "user39"
                        },
                        new
                        {
                            UserId = 40,
                            Email = "user40@example.com",
                            Password = "$2a$11$l7uAIGnVsCjTcvPR9j6Tqeu9ZaKzv72yIHTPiHCaNGjqnwe7xu9Zy",
                            Username = "user40"
                        },
                        new
                        {
                            UserId = 41,
                            Email = "user41@example.com",
                            Password = "$2a$11$hPrR5Je9CJTkcn24BdNwYOLfsl9YCw6G3KZ50i3.eIDUoh6YDA/0m",
                            Username = "user41"
                        },
                        new
                        {
                            UserId = 42,
                            Email = "user42@example.com",
                            Password = "$2a$11$puAExtRaCU2O1d5vDk20W.PtAFgE3WL9YxyCOa130BTbqhBpPCnqG",
                            Username = "user42"
                        },
                        new
                        {
                            UserId = 43,
                            Email = "user43@example.com",
                            Password = "$2a$11$ayPu5rmpQp1kcqBskiFix.OlGlm0xktGCQr3xAjFTL8HGplZSI2qK",
                            Username = "user43"
                        },
                        new
                        {
                            UserId = 44,
                            Email = "user44@example.com",
                            Password = "$2a$11$kiM9I7QveNSgsvKHZcxSAeEhmz/.qBVniF0Z28OXeOpWVEYZl2kGq",
                            Username = "user44"
                        },
                        new
                        {
                            UserId = 45,
                            Email = "user45@example.com",
                            Password = "$2a$11$qcTlSFzYD7PSnJF.w3odmOCYHna2Hu3cM1tfC8hlh5hoRegW29Mly",
                            Username = "user45"
                        },
                        new
                        {
                            UserId = 46,
                            Email = "user46@example.com",
                            Password = "$2a$11$.SnI66qr0CjSkeeqxpU.BOGTAOlyNUQj8pCT5JkxW5Dz69og/tHUi",
                            Username = "user46"
                        },
                        new
                        {
                            UserId = 47,
                            Email = "user47@example.com",
                            Password = "$2a$11$QhnGrg1pcEfjyLQBybSayeqz9DsEnST0CqJKkcWGhpZ/j8qNOcepS",
                            Username = "user47"
                        },
                        new
                        {
                            UserId = 48,
                            Email = "user48@example.com",
                            Password = "$2a$11$FX9YaKPa6meJkp9.ohp71O0kRgoWkYtoPKyHe8wiZDzFW3JiPZC.O",
                            Username = "user48"
                        },
                        new
                        {
                            UserId = 49,
                            Email = "user49@example.com",
                            Password = "$2a$11$Fx397PQsypLPPvt3awfIK.klz.Jv.Vom8UQF2oQDtvjTxfOHjjpLG",
                            Username = "user49"
                        },
                        new
                        {
                            UserId = 50,
                            Email = "user50@example.com",
                            Password = "$2a$11$Dg8ZuJnwG0Tl8/IKGgA8..6RKx0mU7NECJjJUjPr3rme4MpTRJoLy",
                            Username = "user50"
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Db.Models.Item", b =>
                {
                    b.HasOne("InventoryManagementSystem.Db.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.Db.Models.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InventoryManagementSystem.Db.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("InventoryManagementSystem.Db.Models.User", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
