// <auto-generated />
using InventoryManagementSystem.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventoryManagementSystem.Db.Migrations
{
    [DbContext(typeof(InventoryManagementSystemDbContext))]
    partial class InventoryManagementSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryManagementSystem.Db.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 3,
                            Email = "user3@example.com",
                            Password = "$2a$11$v2ohyb/Pa2SqQ1AHRjx/jeFmAjAZF0mWJqfgDv4GGJqeUtVXdiCgK",
                            Username = "user3"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "user4@example.com",
                            Password = "$2a$11$oqU9RI/GxktCGBlDylYuOuVnbvwSDYCga6DxEu37RwMIEtzqF3ZF.",
                            Username = "user4"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "user5@example.com",
                            Password = "$2a$11$9K9KGJ2QC/lvWcacU7LEpu6tVubGpxSgu0QBjDX3QtV6mX4PFB/EG",
                            Username = "user5"
                        },
                        new
                        {
                            UserId = 6,
                            Email = "user6@example.com",
                            Password = "$2a$11$gDobJ882oWFCJ.eszegF4u96QI72v.Qyda1J29MVGR.KrIGN8AgVO",
                            Username = "user6"
                        },
                        new
                        {
                            UserId = 7,
                            Email = "user7@example.com",
                            Password = "$2a$11$ST0FEcrQgEMYTzL3IS2EY.KMUJMxhAEpbGlaYz8te0T1kpNqdkCQ.",
                            Username = "user7"
                        },
                        new
                        {
                            UserId = 8,
                            Email = "user8@example.com",
                            Password = "$2a$11$pGCO.Za5VplhFoWhmRGgq.A5IM7wLv.YZKvTJ23Dh98n2QPc1DHU.",
                            Username = "user8"
                        },
                        new
                        {
                            UserId = 9,
                            Email = "user9@example.com",
                            Password = "$2a$11$Fwy2ZDkdkPbM5vzXYMt82eJp4lmle7X1a7H/TFGtK/qy8of7usm4q",
                            Username = "user9"
                        },
                        new
                        {
                            UserId = 10,
                            Email = "user10@example.com",
                            Password = "$2a$11$rZgP0JGxyav4wNt.9i3o6e0tVKfg8hyqreBBiUP4uj02yeSxz7viK",
                            Username = "user10"
                        },
                        new
                        {
                            UserId = 11,
                            Email = "user11@example.com",
                            Password = "$2a$11$n2uktkQFl7OVHQHHx09rKu/tlovwODAkTa3QxcOso0p6bKStETz5e",
                            Username = "user11"
                        },
                        new
                        {
                            UserId = 12,
                            Email = "user12@example.com",
                            Password = "$2a$11$XtxlATEqsTgGcp9OsprblOY.jtSOjl7SmVU40UDXB0DAMuKQNUYUW",
                            Username = "user12"
                        },
                        new
                        {
                            UserId = 13,
                            Email = "user13@example.com",
                            Password = "$2a$11$4e2kqN3VRkpuGPongyevHe7klYckuFaQugn7k952BOYTvyBOe.hPq",
                            Username = "user13"
                        },
                        new
                        {
                            UserId = 14,
                            Email = "user14@example.com",
                            Password = "$2a$11$PMW5ARCslliSlTOFRD8uLeUOCKChEaWBApA5sm61nqibNoSCdQ5zG",
                            Username = "user14"
                        },
                        new
                        {
                            UserId = 15,
                            Email = "user15@example.com",
                            Password = "$2a$11$JmMOhJOW0OrPxpuZPzHvoOXyoOLtD./Rq7bzluU85F8cPuAFTE9.G",
                            Username = "user15"
                        },
                        new
                        {
                            UserId = 16,
                            Email = "user16@example.com",
                            Password = "$2a$11$jEB8strCMEDrgYuHKZL0S.RW/UHdONYw0no/bqJqQGVi3BPny4aYq",
                            Username = "user16"
                        },
                        new
                        {
                            UserId = 17,
                            Email = "user17@example.com",
                            Password = "$2a$11$36TsLIg6C/9W62AWCvm9puZIvvNqLTf7UpU0IIp4eEb1epnhRIFTu",
                            Username = "user17"
                        },
                        new
                        {
                            UserId = 18,
                            Email = "user18@example.com",
                            Password = "$2a$11$6HZSxVPmBr489eROq5DpuuwQoHHLt6Nt.8IjNkpLg6IuHGQccr9rq",
                            Username = "user18"
                        },
                        new
                        {
                            UserId = 19,
                            Email = "user19@example.com",
                            Password = "$2a$11$BHOlpJTPzSczITFO.emxQ.EHaNp7AVahITMN8t8UPykgX.QemwkAe",
                            Username = "user19"
                        },
                        new
                        {
                            UserId = 20,
                            Email = "user20@example.com",
                            Password = "$2a$11$N8UfyNu/yiMrxBPlsKxvfumkcoyM2ouUrTpf4Dv.BcJGcOf3cin/.",
                            Username = "user20"
                        },
                        new
                        {
                            UserId = 21,
                            Email = "user21@example.com",
                            Password = "$2a$11$oGs32T2/TJQh7XTJsoPDLuSawNTXi2GTIS3REgBUPU/pZ/3nU7J1i",
                            Username = "user21"
                        },
                        new
                        {
                            UserId = 22,
                            Email = "user22@example.com",
                            Password = "$2a$11$5y2uR9KfCbO15YmRaGA8zOvl35fS/w4EtPzAjm8Z5kam4qVEt4OiC",
                            Username = "user22"
                        },
                        new
                        {
                            UserId = 23,
                            Email = "user23@example.com",
                            Password = "$2a$11$YxbJzleav61gWVmgHTSLweuL5ZoFOxEpFX7wV93BjO2rXJ8EF6D/6",
                            Username = "user23"
                        },
                        new
                        {
                            UserId = 24,
                            Email = "user24@example.com",
                            Password = "$2a$11$2e1sqj.npsTPbLjMOKnMyeAbbDEpn3v8XgIbYotyZ3fhwKzbvXINS",
                            Username = "user24"
                        },
                        new
                        {
                            UserId = 25,
                            Email = "user25@example.com",
                            Password = "$2a$11$fAilhsGs/WZhxwiI18R9Cu4v3/Z.T6r1mfc9yNKAsVHgkR8ZlBajK",
                            Username = "user25"
                        },
                        new
                        {
                            UserId = 26,
                            Email = "user26@example.com",
                            Password = "$2a$11$0qmfM4dn3G3965v6CzsGG.aG6YWGNWx5g52/K8FmSK6YJryA.G4Qu",
                            Username = "user26"
                        },
                        new
                        {
                            UserId = 27,
                            Email = "user27@example.com",
                            Password = "$2a$11$PV1AqFX4OH/yVHiUuJsHu.7RqU14uswm23ucv4S4JkFsoZ6dOyM6a",
                            Username = "user27"
                        },
                        new
                        {
                            UserId = 28,
                            Email = "user28@example.com",
                            Password = "$2a$11$AcFz0VvRba0VidyhR/I5ju7dYMkUL/wDdDLaDF4K6BjbSceLZXnBi",
                            Username = "user28"
                        },
                        new
                        {
                            UserId = 29,
                            Email = "user29@example.com",
                            Password = "$2a$11$p3Hynr0xkPJPLJkmCF42O.Je7ug/bjQNlkRtRD4IsE.HJDKtYgt6i",
                            Username = "user29"
                        },
                        new
                        {
                            UserId = 30,
                            Email = "user30@example.com",
                            Password = "$2a$11$Q0MTlJ.hNB7BbfU5aZ9ol.UdEqhX8tHkqCUcYROlqCDFUB0r5LKvu",
                            Username = "user30"
                        },
                        new
                        {
                            UserId = 31,
                            Email = "user31@example.com",
                            Password = "$2a$11$4IDszYAlhuj33PdS85WWQ.JqVa3NIyBSjLTqkygdev5cBzzmgLtKy",
                            Username = "user31"
                        },
                        new
                        {
                            UserId = 32,
                            Email = "user32@example.com",
                            Password = "$2a$11$zf.MMQzpW.0Bf1Y.AGTXduFGNHkgwWp/G1CUO3oS8wQ1CbPYBOwWW",
                            Username = "user32"
                        },
                        new
                        {
                            UserId = 33,
                            Email = "user33@example.com",
                            Password = "$2a$11$qRjcOgISoPHKWKjKyA84FO62MYOwFstxhefFqJKT24rrNxKsRQrc2",
                            Username = "user33"
                        },
                        new
                        {
                            UserId = 34,
                            Email = "user34@example.com",
                            Password = "$2a$11$f/4whBQ3RSQWLc5IH6YrbOO8rQmhreWbQoZDRW6034WcpLJK8nNHO",
                            Username = "user34"
                        },
                        new
                        {
                            UserId = 35,
                            Email = "user35@example.com",
                            Password = "$2a$11$4UBT4rxnU9faFekvtnsE5e5LPUqWp5pKxo/.vr.5tqeFZkpf5HWU.",
                            Username = "user35"
                        },
                        new
                        {
                            UserId = 36,
                            Email = "user36@example.com",
                            Password = "$2a$11$x39/wluAjyiYqS2NZaBdsuREUu/BFZID.N3jdnN/L5QOuEg1TuTdK",
                            Username = "user36"
                        },
                        new
                        {
                            UserId = 37,
                            Email = "user37@example.com",
                            Password = "$2a$11$4kdoIiOakyX2mo65LGZ82OaFVQLHdyC3bUMtv.Q7Nv2oMZo6WpPvm",
                            Username = "user37"
                        },
                        new
                        {
                            UserId = 38,
                            Email = "user38@example.com",
                            Password = "$2a$11$askML/3o7AiQXS7uk3GMy.1wCsrO8H1wecc/KsytGqNNCKL/oriI2",
                            Username = "user38"
                        },
                        new
                        {
                            UserId = 39,
                            Email = "user39@example.com",
                            Password = "$2a$11$fakivwGVcJ5.l03OZtR82u7GvlHXKNW9zsUuJKuME4QoeQag.ctA.",
                            Username = "user39"
                        },
                        new
                        {
                            UserId = 40,
                            Email = "user40@example.com",
                            Password = "$2a$11$Z0KgsrQ9aWptC14THW4/suRWngIu2HAJ58WRfLALZCkmdFi68h7qW",
                            Username = "user40"
                        },
                        new
                        {
                            UserId = 41,
                            Email = "user41@example.com",
                            Password = "$2a$11$yehScc5r7btox7rKmR909eDvyl5Cj2KvayzmvdJPCJuUgKw62u8Y2",
                            Username = "user41"
                        },
                        new
                        {
                            UserId = 42,
                            Email = "user42@example.com",
                            Password = "$2a$11$vjqptpMv1gdN8txAarlcZuEuQSuEL2Q4pPsAoQJKeocgya1MTTcgm",
                            Username = "user42"
                        },
                        new
                        {
                            UserId = 43,
                            Email = "user43@example.com",
                            Password = "$2a$11$fYNQ.IETmcL5WcxvU0ymru2JbLlL1595oLHijAMmyE6Bg4itFYCaO",
                            Username = "user43"
                        },
                        new
                        {
                            UserId = 44,
                            Email = "user44@example.com",
                            Password = "$2a$11$Dp5ARF/wrarTUmlxQiGt0e6A3Gwnqm3DRwW700ByUJxNVfChFPXAG",
                            Username = "user44"
                        },
                        new
                        {
                            UserId = 45,
                            Email = "user45@example.com",
                            Password = "$2a$11$uuVQab4xu24wTJrJQLuBDOV6pGM.MLoPSDo46cwAAfA9lRymFmFpS",
                            Username = "user45"
                        },
                        new
                        {
                            UserId = 46,
                            Email = "user46@example.com",
                            Password = "$2a$11$sRTSDdh.zBEHrEfEI5frPuQUxWl40pD3yaGFgjj1VFdMXPlUrPkPu",
                            Username = "user46"
                        },
                        new
                        {
                            UserId = 47,
                            Email = "user47@example.com",
                            Password = "$2a$11$g21UMf4o1ohaLtrcpUnMhe/xs.mh4gGDr1CTd7rN5J02sMfri.QlW",
                            Username = "user47"
                        },
                        new
                        {
                            UserId = 48,
                            Email = "user48@example.com",
                            Password = "$2a$11$OkRzkKrbGp7FXVpn5Qpf0uqyFWFhfUJ/b6GWaq3jMGt.795wT9DpK",
                            Username = "user48"
                        },
                        new
                        {
                            UserId = 49,
                            Email = "user49@example.com",
                            Password = "$2a$11$5V..j6VFtbgANYZDhCZn.ujjPwk8.66CuZbyxq0V72kfrAugXfc6C",
                            Username = "user49"
                        },
                        new
                        {
                            UserId = 50,
                            Email = "user50@example.com",
                            Password = "$2a$11$tek2nQBEu8zHiibIc9izY.ke1DwFLUHW0tq5Kw5z79QkD/XAprRIG",
                            Username = "user50"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
